### ISSUE TITLE
[Cleanup] Remove .vscode from GitHub repo

### ISSUE THREAD

**Issue by mak448a** [CyanVoxel/TagStudio#28]
`.vscode` is already in the `.gitignore`. If you would like to keep the folder, you should remove line `.vscode` from your `.gitignore`.

**Comment by CyanVoxel** [comment]
The `launch.json` is intended to be included with the project as a way for other people to launch the program from VSCode with the same configuration. It's one of the few files inside the `.vscode` folder that are allowed through to the repo. I may remove some of the other VScode whitelists from the `.gitignore`, but for now the `launch.json` is intended to be there.

```
### VisualStudioCode ###
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
```
