### ISSUE TITLE
Cannot Create Library on network path

### ISSUE THREAD

**Issue by Loran425** [CyanVoxel/TagStudio#29]
https://github.com/CyanVoxel/TagStudio/blob/45e765862d7ec2bf2928134a91f0251a4d0b2068/tagstudio/src/core/library.py#L534-L543

Strips leading `//` from server shares e.g. `//<server>/<share>` gets normalized to `\\\\<server>\\<share>` but then gets caught by the above line stripping the leading `\\` which in turn causes 
https://github.com/CyanVoxel/TagStudio/blob/45e765862d7ec2bf2928134a91f0251a4d0b2068/tagstudio/src/core/library.py#L560-L571
to fail as the address is no longer accurate 

swapping from strip to rstrip only removes trailing `\\` 
`path = os.path.normpath(path).strip('\\')` becomes 
`path = os.path.normpath(path).rstrip('\\')`
Which works for network shares.

**Comment by CyanVoxel** [comment]
Change merged in #30 ! Thanks for the contribution!
