### ISSUE TITLE
[BUG] Favorite and Archive tags are duplicated inside library files

### ISSUE THREAD

**Issue by CyanVoxel** [CyanVoxel/TagStudio#38]
As the title says, duplicate tag data for the built-in tags are accruing over time inside of library files. This is likely due to a failure in the check system for built-in tags, thinking that the built-in tags are missing from the library when they're not.
![image](https://github.com/CyanVoxel/TagStudio/assets/46939827/a87adba3-9782-4df7-a541-5c4c61307986)

**Comment by Thesacraft** [comment]
Found it. #39 should fix it. You checked for default tags while converting to json before adding any tags to the list that gets checked
