### ISSUE TITLE
[BUG]  visual bootup thing

### ISSUE THREAD

**Issue by OleMortensen8** [CyanVoxel/TagStudio#9]
It probably is only on linux but i'd still like to mention it. 
Linux works fine just need a boot script into virtual environment. 

there's a boot issue  that i'm not sure is only a linux thing or also in windows.:
it looks like this first time i booted it up is that normal:
![Screenshot_20240423_065150](https://github.com/CyanVoxel/TagStudio/assets/22987563/c9d16983-555a-4a00-a8c4-a1df1f912ce9)

otherwise if it's not I'd not mind writing bootup script for linux.
And the UI 'glitch' if it's not suposed to look like that. **minding that it only does it until files are added**
![Screenshot_20240423_064855](https://github.com/CyanVoxel/TagStudio/assets/22987563/74aa9557-8fd9-4d53-9a10-d5bc7df723dd)

**Comment by CyanVoxel** [comment]
The good news: It's not just Linux, this is just how it looks like for me too :) It started after something I did a while back, but I haven't gotten around to fixing it.
The bad news: It's still a bug that I need to fix :)

**Comment by OleMortensen8** [comment]
good to know. that means it'll be fixable.

**Comment by CyanVoxel** [comment]
Fixed in #22! Thanks, @Thesacraft !
